# softfloat.cmake — FetchContent wrapper for Berkeley SoftFloat 3e
#
# Fetches and builds SoftFloat as a static library with automatic
# platform detection. Provides the `softfloat` target.
#
# SoftFloat source: https://github.com/ucb-bar/berkeley-softfloat-3

include(FetchContent)

FetchContent_Declare(
    softfloat
    GIT_REPOSITORY https://github.com/ucb-bar/berkeley-softfloat-3.git
    GIT_TAG        a0c6494cdc11865811dec815d5c0049fba9d82a8
)

FetchContent_GetProperties(softfloat)
if(NOT softfloat_POPULATED)
    FetchContent_Populate(softfloat)
endif()

# ---------------------------------------------------------------------------
# Architecture detection
# ---------------------------------------------------------------------------
# Select SoftFloat specialization directory based on host processor.
if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64")
    set(SOFTFLOAT_SPECIALIZE "8086-SSE")
    set(SOFTFLOAT_FAST_INT64 TRUE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3-6]86|x86")
    set(SOFTFLOAT_SPECIALIZE "8086")
    set(SOFTFLOAT_FAST_INT64 FALSE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
    set(SOFTFLOAT_SPECIALIZE "ARM-VFPv2")
    set(SOFTFLOAT_FAST_INT64 TRUE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|ARM")
    set(SOFTFLOAT_SPECIALIZE "ARM-VFPv2")
    set(SOFTFLOAT_FAST_INT64 FALSE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "riscv64")
    set(SOFTFLOAT_SPECIALIZE "RISCV")
    set(SOFTFLOAT_FAST_INT64 TRUE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "riscv32")
    set(SOFTFLOAT_SPECIALIZE "RISCV")
    set(SOFTFLOAT_FAST_INT64 FALSE)
else()
    message(WARNING "SoftFloat: unknown processor '${CMAKE_SYSTEM_PROCESSOR}', "
                    "defaulting to 8086-SSE")
    set(SOFTFLOAT_SPECIALIZE "8086-SSE")
    set(SOFTFLOAT_FAST_INT64 TRUE)
endif()

message(STATUS "SoftFloat: specialize=${SOFTFLOAT_SPECIALIZE}, "
               "FAST_INT64=${SOFTFLOAT_FAST_INT64}")

set(SF_SOURCE_DIR "${softfloat_SOURCE_DIR}/source")

# ---------------------------------------------------------------------------
# Collect source files
# ---------------------------------------------------------------------------
# file(GLOB) is safe here: sources are at a pinned commit via FetchContent,
# so the file set is deterministic. Re-running cmake is required if the
# pinned commit changes, which is already the case for any FetchContent
# change.

# Platform-independent sources (non-recursive — source/*.c only)
file(GLOB SF_COMMON_SOURCES "${SF_SOURCE_DIR}/*.c")

# Architecture-specific sources
file(GLOB SF_ARCH_SOURCES "${SF_SOURCE_DIR}/${SOFTFLOAT_SPECIALIZE}/*.c")

# The source directory contains internal helpers for both the FAST_INT64 and
# multi-word builds. These are mutually exclusive — exclude the wrong set.
if(SOFTFLOAT_FAST_INT64)
    set(_SF_EXCLUDE
        addCarryM addComplCarryM addExtF80M addF128M addM
        compare128M compare96M compareNonnormExtF80M
        invalidExtF80M invalidF128M isNaNF128M
        mul128MTo256M mul64To128M mulAddF128M negXM
        normExtF80SigM normRoundPackMToExtF80M normRoundPackMToF128M
        normSubnormalF128SigM remStepMBy32
        roundMToI64 roundMToUI64 roundPackMToExtF80M roundPackMToF128M
        shiftLeftM shiftNormSigF128M shiftRightJamM shiftRightM
        shortShiftLeft64To96M shortShiftLeftM shortShiftRightExtendM
        shortShiftRightJamM shortShiftRightM
        sub1XM subM tryPropagateNaNExtF80M tryPropagateNaNF128M
    )
    list(TRANSFORM _SF_EXCLUDE PREPEND "${SF_SOURCE_DIR}/s_")
    list(TRANSFORM _SF_EXCLUDE APPEND ".c")
    list(REMOVE_ITEM SF_COMMON_SOURCES ${_SF_EXCLUDE})
endif()

# ---------------------------------------------------------------------------
# Generate platform.h
# ---------------------------------------------------------------------------
# SoftFloat expects a platform.h in the include path. Each upstream build
# directory ships its own; we generate one based on detected properties.

set(SF_PLATFORM_DIR "${CMAKE_CURRENT_BINARY_DIR}/softfloat_platform")
file(MAKE_DIRECTORY "${SF_PLATFORM_DIR}")

include(TestBigEndian)
test_big_endian(SF_BIG_ENDIAN)
if(SF_BIG_ENDIAN)
    set(SF_ENDIAN_DEF "BIGENDIAN")
else()
    set(SF_ENDIAN_DEF "LITTLEENDIAN")
endif()

set(_SF_PLATFORM_H "/* Generated by OPINE cmake/softfloat.cmake */\n")
string(APPEND _SF_PLATFORM_H "#define ${SF_ENDIAN_DEF} 1\n\n")

# INLINE definition
string(APPEND _SF_PLATFORM_H
    "#if defined(_MSC_VER)\n"
    "#define INLINE static __inline\n"
    "#elif defined(__GNUC_STDC_INLINE__)\n"
    "#define INLINE inline\n"
    "#else\n"
    "#define INLINE extern inline\n"
    "#endif\n\n")

# Compiler-specific optimizations
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    string(APPEND _SF_PLATFORM_H "#define SOFTFLOAT_BUILTIN_CLZ 1\n")
    if(SOFTFLOAT_FAST_INT64)
        string(APPEND _SF_PLATFORM_H "#define SOFTFLOAT_INTRINSIC_INT128 1\n")
    endif()
    string(APPEND _SF_PLATFORM_H "#include \"opts-GCC.h\"\n")
endif()

file(WRITE "${SF_PLATFORM_DIR}/platform.h" "${_SF_PLATFORM_H}")

# ---------------------------------------------------------------------------
# Build static library
# ---------------------------------------------------------------------------
add_library(softfloat STATIC ${SF_COMMON_SOURCES} ${SF_ARCH_SOURCES})
set_target_properties(softfloat PROPERTIES LINKER_LANGUAGE C)

target_include_directories(softfloat
    PRIVATE
        "${SF_SOURCE_DIR}/${SOFTFLOAT_SPECIALIZE}"
    PUBLIC
        "${SF_PLATFORM_DIR}"
        "${SF_SOURCE_DIR}/include"
)

target_compile_definitions(softfloat PRIVATE
    SOFTFLOAT_ROUND_ODD
    INLINE_LEVEL=5
    SOFTFLOAT_FAST_DIV32TO16
    SOFTFLOAT_FAST_DIV64TO32
)

if(SOFTFLOAT_FAST_INT64)
    target_compile_definitions(softfloat PUBLIC SOFTFLOAT_FAST_INT64)
endif()

# Endianness must be PUBLIC so that consumers see the correct struct layout
# in softfloat_types.h (which uses #ifdef LITTLEENDIAN / BIGENDIAN to order
# fields of extFloat80_t and float128_t).
target_compile_definitions(softfloat PUBLIC ${SF_ENDIAN_DEF})

# Match upstream: -O2 is required so that INLINE functions from opts-GCC.h
# are actually inlined (C inline semantics need optimization enabled).
# Also suppress warnings from third-party C code.
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    target_compile_options(softfloat PRIVATE -O2 -w)
elseif(MSVC)
    target_compile_options(softfloat PRIVATE /O2 /w)
endif()
