# testfloat.cmake — FetchContent wrapper for Berkeley TestFloat 3e
#
# Fetches and builds the TestFloat core library for linking into OPINE's
# test harness. Depends on the `softfloat` target from softfloat.cmake.
#
# TestFloat source: https://github.com/ucb-bar/berkeley-testfloat-3

include(FetchContent)

FetchContent_Declare(
    testfloat
    GIT_REPOSITORY https://github.com/ucb-bar/berkeley-testfloat-3.git
    GIT_TAG        a9c849f1b0eb0264b626d9686ffae167d996e3be
)

FetchContent_GetProperties(testfloat)
if(NOT testfloat_POPULATED)
    FetchContent_Populate(testfloat)
endif()

set(TF_SOURCE_DIR "${testfloat_SOURCE_DIR}/source")

# ---------------------------------------------------------------------------
# Generate platform.h
# ---------------------------------------------------------------------------
# TestFloat also expects a platform.h. Reuse endianness detection from
# softfloat.cmake (SF_ENDIAN_DEF is already set).

set(TF_PLATFORM_DIR "${CMAKE_CURRENT_BINARY_DIR}/testfloat_platform")
file(MAKE_DIRECTORY "${TF_PLATFORM_DIR}")

set(_TF_PLATFORM_H "/* Generated by OPINE cmake/testfloat.cmake */\n")
string(APPEND _TF_PLATFORM_H "#define ${SF_ENDIAN_DEF} 1\n\n")
string(APPEND _TF_PLATFORM_H
    "#if defined(_MSC_VER)\n"
    "#define INLINE static __inline\n"
    "#elif defined(__GNUC_STDC_INLINE__)\n"
    "#define INLINE inline\n"
    "#else\n"
    "#define INLINE extern inline\n"
    "#endif\n")

file(WRITE "${TF_PLATFORM_DIR}/platform.h" "${_TF_PLATFORM_H}")

# ---------------------------------------------------------------------------
# Collect source files
# ---------------------------------------------------------------------------
# Core library infrastructure (matches OBJS_LIB in upstream Makefile)
set(TF_LIB_SOURCES
    ${TF_SOURCE_DIR}/uint128_inline.c
    ${TF_SOURCE_DIR}/uint128.c
    ${TF_SOURCE_DIR}/fail.c
    ${TF_SOURCE_DIR}/functions_common.c
    ${TF_SOURCE_DIR}/functionInfos.c
    ${TF_SOURCE_DIR}/standardFunctionInfos.c
    ${TF_SOURCE_DIR}/random.c
    ${TF_SOURCE_DIR}/genCases_common.c
    ${TF_SOURCE_DIR}/genCases_ui32.c
    ${TF_SOURCE_DIR}/genCases_ui64.c
    ${TF_SOURCE_DIR}/genCases_i32.c
    ${TF_SOURCE_DIR}/genCases_i64.c
    ${TF_SOURCE_DIR}/genCases_f16.c
    ${TF_SOURCE_DIR}/genCases_bf16.c
    ${TF_SOURCE_DIR}/genCases_f32.c
    ${TF_SOURCE_DIR}/genCases_f64.c
    ${TF_SOURCE_DIR}/genCases_extF80.c
    ${TF_SOURCE_DIR}/genCases_f128.c
    ${TF_SOURCE_DIR}/genCases_writeTestsTotal.c
    ${TF_SOURCE_DIR}/verCases_inline.c
    ${TF_SOURCE_DIR}/verCases_common.c
    ${TF_SOURCE_DIR}/verCases_writeFunctionName.c
    ${TF_SOURCE_DIR}/readHex.c
    ${TF_SOURCE_DIR}/writeHex.c
    ${TF_SOURCE_DIR}/testLoops_common.c
)

# writeCase and test loop sources (numerous, follow clear naming patterns)
file(GLOB TF_WRITECASE_SOURCES "${TF_SOURCE_DIR}/writeCase_*.c")
file(GLOB TF_TEST_SOURCES
    "${TF_SOURCE_DIR}/test_a_*.c"
    "${TF_SOURCE_DIR}/test_ab_*.c"
    "${TF_SOURCE_DIR}/test_abcz_*.c"
    "${TF_SOURCE_DIR}/test_az_*.c"
    "${TF_SOURCE_DIR}/test_abz_*.c"
)

# ---------------------------------------------------------------------------
# Build the core TestFloat library
# ---------------------------------------------------------------------------
# Target name is testfloat_lib (not testfloat) to avoid collision with
# the upstream testfloat executable name.
add_library(testfloat_lib STATIC
    ${TF_LIB_SOURCES}
    ${TF_WRITECASE_SOURCES}
    ${TF_TEST_SOURCES}
)

set_target_properties(testfloat_lib PROPERTIES LINKER_LANGUAGE C)

target_include_directories(testfloat_lib
    PRIVATE "${TF_PLATFORM_DIR}"
    PUBLIC "${TF_SOURCE_DIR}"
)

target_link_libraries(testfloat_lib PUBLIC softfloat)

target_compile_definitions(testfloat_lib PRIVATE
    FLOAT16
    BFLOAT16
    FLOAT64
    EXTFLOAT80
    FLOAT128
    FLOAT_ROUND_ODD
)

# Suppress warnings from third-party C code
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    target_compile_options(testfloat_lib PRIVATE -w)
elseif(MSVC)
    target_compile_options(testfloat_lib PRIVATE /w)
endif()
